# Assignment 1
1. Import the Numpy package under the name np
2. Create a null vector of size 10
3. Create a null vector of size 10 but the fifth value which is 1
4. Create a vector with values ranging from 10 to 49
5. Reverse a vector (the first element becomes last)
6. Create a 3x3 matrix with values ranging from 0 to 8
7. Find indices of non­zero elements from [1,2,0,0,4,0]
8. Create a 3x3x3 array with random values
10. Create a random vector of size 30 and find the mean value
11. Create a 2d array with 1 on the border and 0 inside
12. Create an 8x8 matrix and fill it with a checkerboard pattern
13. What is the major difference between sets, lists, tuples and dictionaries?
14. Print first 10 natural numbers using while loop
15. Print the numbers -10 to -1 using for loop.
16. Print the message “Done” after successful execution of any for a loop. 
17. Create a random vector of size 10 and sort it
18. Execute any three math functions using NumPy.

Import the Numpy package under the name np
 and Create a null vector of size 10

In [1]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1

In [2]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [4]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Reverse a vector (the first element becomes last

In [10]:
x_rev = np.flip(x)
x_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
#Alternatively
x_rev = x[::-1]
x_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non­zero elements from [1,2,0,0,4,0]

In [13]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

Create a 3x3x3 array with random values

In [16]:
from numpy import random
x = random.randint(100, size=(3, 3,3))
x

array([[[57, 93, 75],
        [78, 37, 74],
        [90, 63, 78]],

       [[14, 33, 62],
        [24,  9, 48],
        [33, 18, 70]],

       [[53,  1, 36],
        [ 3, 91, 52],
        [51, 35, 58]]])

Create a random vector of size 30 and find the mean value


In [21]:
x = random.randint(100, size = 30)
print(x)
np.mean(x)

[ 9 60 35 59 72 97 75 17 80 78 43 14 90 97 80 82 71 23 32 69 26 94 10 44
  8  4 72  0 65 33]


51.3

Create a 2d array with 1 on the border and 0 inside

In [25]:
#2d array of just 1
x = np.ones((6,6))
#zeros on the inside
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Create an 8x8 matrix and fill it with a checkerboard pattern

In [29]:
#an array of zeros
x = np.zeros((8, 8), dtype = int) 

#input 1 to create checkerboard
x[1::2, ::2] = 1
x[::2, 1::2] = 1

x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

What is the major difference between sets, lists, tuples and dictionaries?

- Set: A Set is an unordered collection data type that is iterable, mutable and has no duplicate elements.

- Dictionary: in Python is an unordered collection of data values, used to store data values like a map, which unlike other Data Types that hold only single value as an element, Dictionary holds key:value pair. 

- Lists: are just like dynamic sized arrays, declared in other languages (vector in C++ and ArrayList in Java). Lists need not be homogeneous always which makes it a most powerful tool in Python.

- Tuple: A Tuple is a collection of Python objects separated by commas. In someways a tuple is similar to a list in terms of indexing, nested objects and repetition but a tuple is immutable unlike lists that are mutable.

Print first 10 natural numbers using while loop

In [30]:
i = 1 
while i <=10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


Print the numbers -10 to -1 using for loop.

In [32]:
for i in range(-10, 0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


Print the message “Done” after successful execution of any for a loop.

In [33]:
for x in range(1, 9, 4):
    print(x)
print('Done')

1
5
Done


Create a random vector of size 10 and sort it


In [35]:
x = random.randint(100, size = 10)
np.sort(x)

array([24, 25, 27, 47, 48, 81, 81, 92, 98, 98])

Execute any three math functions using NumPy.

In [39]:
import math
x = math.pi

round(x)

3

In [41]:
np.around(x)

3.0

In [42]:
np.ceil(x)

4.0

In [43]:
np.exp(x)

23.140692632779267